[package]
name = "lr-derive"
version = "0.1.0"
edition = "2021"
workspace = ".."

[lib]
proc-macro = true

[dependencies]
lr-core = { path = "../lr-core" }
syn = { version = "1.0", features = ["derive", "parsing", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
